routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

// Admin routes
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function() {
	Route::get('login', 'LoginController@index');
	Route::post('login', 'LoginController@login')->name('admin.login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	Route::group(['middleware' => 'admin'], function() {
		Route::get('/', 'DashboardController@index')->name('admin.dashboard');
		Route::resources([
			'area_maps' => 'AreaMapController',
			'raw_materials' => 'RawMaterialController'
		]);
	});
});

// Site routes
Route::group(['prefix' => '', 'namespace' => 'Site'], function() {
	Route::get('/', 'HomeController@index')->name('homepage');
});

app/AreaMap.php
<?php

namespace EvolveAdmin;

use Illuminate\Database\Eloquent\Model;

class AreaMap extends Model
{
	protected $fillable = [
		'scale',
		'size_x',
		'size_y',
		'map_data',
		'x',
		'y',
	];
}

app/Http/Controllers/Admin/AreaMapController.php
<?php

namespace EvolveAdmin\Http\Controllers\Admin;

use EvolveAdmin\AreaMap;
use EvolveAdmin\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class AreaMapController extends Controller
{
	/**
	 * Display a listing of the resource.
	 */
	public function index(): View
	{
		$areaMaps = AreaMap::all();

		return view('admin.area_maps.index', compact('areaMaps'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return View
	 */
	public function create(): View
	{
		return view('admin.area_maps.create');
	}

	/**
	 * Store a newly created resource in storage.
	 */
	public function store(Request $request): RedirectResponse
	{
		$request->validate([
			'scale' => 'required',
			'size_x' => 'required',
			'size_y' => 'required',
			'x' => 'required',
			'y' => 'required',
		]);

		$areaMap = new AreaMap([
			'scale' => $request->get('scale'),
			'size_x' => $request->get('size_x'),
			'size_y' => $request->get('size_y'),
			'map_data' => json_encode([1, 2, 3, 4]),
			'x' => $request->get('x'),
			'y' => $request->get('y'),
		]);

		$areaMap->save();

		return redirect(route('area_maps.index'))->with('success', 'Area map created!');
	}

	/**
	 * Display the specified resource.
	 */
	public function show(int $id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 */
	public function edit(int $id): View
	{
		$areaMap = AreaMap::find($id);

		return view('admin.area_maps.edit', compact('areaMap'));
	}

	/**
	 * Update the specified resource in storage.
	 */
	public function update(Request $request, int $id): RedirectResponse
	{
		$request->validate([
			'scale' => 'required',
			'size_x' => 'required',
			'size_y' => 'required',
			'x' => 'required',
			'y' => 'required',
		]);

		$areaMap = AreaMap::find($id);
		$areaMap->scale = $request->get('scale');
		$areaMap->size_x = $request->get('size_x');
		$areaMap->size_y = $request->get('size_y');
		$areaMap->y = $request->get('y');
		$areaMap->save();

		return redirect(route('area_maps.index'))->with('success', _i('Area map \'%d\' updated!', $id));
	}

	/**
	 * Remove the specified resource from storage.
	 */
	public function destroy(int $id): RedirectResponse
	{
		$areaMap = AreaMap::find($id);
		$areaMap->delete();

		return redirect(route('area_maps.index'))->with('success', _i('Area map \'%d\' was deleted!', $id));
	}
}

resources/views/admin/area_maps/create.blade.php
@extends('admin.layouts._layout')

@section('breadcrumbs')
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">{{ _i('Create area map') }}</h3> </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/admin') }}">{{ _i('Admin start page') }}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('area_maps.index') }}">{{ _i('Area maps') }}</a></li>
                <li class="breadcrumb-item active">{{ _i('Create') }}</li>
            </ol>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
    </div>
@stop

@section('content')
<div class="basic-form">
    <form method="POST" action="{{ route('area_maps.store') }}">
        @csrf
        <div class="form-group form-row">
            <div class="col-lg-12">
                <h4>{{ _i('Scale of the game level') }}</h4>
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="scale" class="col-lg-3 control-label">{{ _i('Scale') }}</label>
                <input type="number" min="1" value="1" class="form-control" id="scale" name="scale"
                       placeholder="{{ _i('Scale number') }}" aria-describedby="scaleHelp">
                <small id="scaleHelp" class="form-text text-muted">{{ _i('Scale equal of game level') }}</small>
            </div>
        </div>

        <div class="form-group form-row">
            <div class="col-lg-12">
                <h4>{{ _i('Sizes') }}</h4>
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="size_x" class="col-lg-3 col-form-label control-label">{{ _i('Width') }}</label>
                <input type="number" min="1" value="9" class="form-control" id="size_x" name="size_x"
                       placeholder="{{ _i('Width of area map') }}">
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="size_y" class="col-lg-3 col-form-label control-label">{{ _i('Height') }}</label>
                <input type="number" min="1" value="9" class="form-control" id="size_y" name="size_y"
                       placeholder="{{ _i('Height of area map') }}">
            </div>
        </div>

        <div class="form-group form-row">
            <div class="col-lg-12">
                <h4>{{ _i('Coordinates') }}</h4>
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="coordinate_x" class="col-lg-3 control-label">{{ _i('Start x') }}</label>
                <input type="number" min="0" value="0" class="form-control" id="coordinate_x" name="x"
                       placeholder="{{ _i('Start x coordinate') }}">
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="coordinate_y" class="col-lg-3 control-label">{{ _i('Start y') }}</label>
                <input type="number" min="0" value="0" class="form-control" id="coordinate_y" name="y"
                       placeholder="{{ _i('Start y coordinate') }}">
            </div>
        </div>

        <input type="submit" class="btn btn-info float-lg-right" value="{{ _i('Add area map') }}">
    </form>
</div>
@endsection

resources/views/admin/area_maps/edit.blade.php
@extends('admin.layouts._layout')

@section('breadcrumbs')
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">{{ _i('Edit area map') }}</h3> </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/admin') }}">{{ _i('Admin start page') }}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('area_maps.index') }}">{{ _i('Area maps') }}</a></li>
                <li class="breadcrumb-item active">{{ _i('Edit') }}</li>
            </ol>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
    </div>
@stop

@section('content')
<div class="basic-form">
    <form method="POST" action="{{ route('area_maps.update', $areaMap->id) }}">
        @method('PUT')
        @csrf
        <div class="form-group form-row">
            <div class="col-lg-12">
                <h4>{{ _i('Scale of the game level') }}</h4>
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="scale" class="col-lg-3 control-label">{{ _i('Scale') }}</label>
                <input type="number" min="1" value="{{ $areaMap->scale }}" class="form-control" id="scale" name="scale"
                       placeholder="{{ _i('Scale number') }}" aria-describedby="scaleHelp">
                <small id="scaleHelp" class="form-text text-muted">{{ _i('Scale equal of game level') }}</small>
            </div>
        </div>

        <div class="form-group form-row">
            <div class="col-lg-12">
                <h4>{{ _i('Sizes') }}</h4>
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="size_x" class="col-lg-3 col-form-label control-label">{{ _i('Width') }}</label>
                <input type="number" min="1" value="{{ $areaMap->size_x }}" class="form-control" id="size_x" name="size_x"
                       placeholder="{{ _i('Width of area map') }}">
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="size_y" class="col-lg-3 col-form-label control-label">{{ _i('Height') }}</label>
                <input type="number" min="1" value="{{ $areaMap->size_y }}" class="form-control" id="size_y" name="size_y"
                       placeholder="{{ _i('Height of area map') }}">
            </div>
        </div>

        <div class="form-group form-row">
            <div class="col-lg-12">
                <h4>{{ _i('Coordinates') }}</h4>
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="coordinate_x" class="col-lg-3 control-label">{{ _i('Start x') }}</label>
                <input type="number" min="0" value="{{ $areaMap->x }}" class="form-control" id="coordinate_x" name="x"
                       placeholder="{{ _i('Start x coordinate') }}">
            </div>
            <div class="form-inline col-lg-6 text-center">
                <label for="coordinate_y" class="col-lg-3 control-label">{{ _i('Start y') }}</label>
                <input type="number" min="0" value="{{ $areaMap->y }}" class="form-control" id="coordinate_y" name="y"
                       placeholder="{{ _i('Start y coordinate') }}">
            </div>
        </div>

        <input type="submit" class="btn btn-info float-lg-right" value="{{ _i('Edit area map') }}">
    </form>
</div>
@endsection

resources/views/admin/area_maps/index.blade.php
@extends('admin.layouts._layout')

@section('breadcrumbs')
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">{{ _i('Create area map')  }}</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.dashboard')  }}">{{ _i('Admin start page') }}</a></li>
                <li class="breadcrumb-item"><a href="{{ route('area_maps.index')  }}">{{ _i('Area maps')  }}</a></li>
            </ol>
        </div>

        <div class="col-sm-12">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br/>
            @endif

            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
    </div>
@stop

@section('content')
    <div>
        <a style="margin: 19px;" href="{{ route('area_maps.create')}}" class="btn btn-primary">{{ _i('New area map') }}</a>
    </div>
    <table class="table table-striped">
    <thead>
    <tr>
        <td>{{ _i('ID') }}</td>
        <td>{{ _i('Scale') }}</td>
        <td>{{ _i('Sizes') }}</td>
        <td>{{ _i('Coordinates') }}</td>
        <td colspan = 2>{{ _i('Actions') }}</td>
    </tr>
    </thead>
    <tbody>
    @foreach($areaMaps as $areaMap)
        <tr>
            <td>{{ $areaMap->id }}</td>
            <td>{{ $areaMap->scale }}</td>
            <td>{{ $areaMap->width }} x {{ $areaMap->height }}</td>
            <td>{{ $areaMap->x }} : {{ $areaMap->y }}</td>
            <td>
                <a href="{{ route('area_maps.edit',$areaMap->id) }}" class="btn btn-primary">{{ _i('Edit') }}</a>
            </td>
            <td>
                <form action="{{ route('area_maps.destroy', $areaMap->id) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">{{ _i('Delete') }}</button>
                </form>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
@endsection