routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

// Admin routes
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function() {
	Route::get('login', 'LoginController@index');
	Route::post('login', 'LoginController@login')->name('admin.login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	Route::group(['middleware' => 'admin'], function() {
		Route::get('/', 'DashboardController@index')->name('admin.dashboard');
		Route::resources([
			'area_maps' => 'AreaMapController',
			'raw_materials' => 'RawMaterialController'
		]);
	});
});

// Site routes
Route::group(['prefix' => '', 'namespace' => 'Site'], function() {
	Route::get('/', 'HomeController@index')->name('homepage');
});

resources/views/admin/layouts/_layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('admin.layouts.meta')

    @include('admin.layouts.styles')
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('/admin/images/favicon.png') }}">
{{--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">--}}
{{--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">--}}
{{--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/fontawesome.min.css">--}}
    <title>Laravel Ela Admin</title>
</head>
<body class="fix-header fix-sidebar">
<!--<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
    </svg>
</div>-->

<div id="main-wrapper" class="container">
    @include('admin.layouts.header')

    <div class="page-wrapper container-fluid">
        <div class="row">
            <div class="left-sidebar col-3 bg-light">
                @include('admin.layouts.sidebar')
            </div>
            <div class="col-9">
                @yield('breadcrumbs')
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            @yield('content')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        @include('admin.layouts.footer')
    </footer>
</div>

@include('admin.layouts.scripts')

</body>
</html>

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ _i('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin.login') }}">{{ _i('Login') }}</a>
                            </li>
                            @if (\Illuminate\Support\Facades\Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ _i('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ \Illuminate\Support\Facades\Auth::user()->name ?: \Illuminate\Support\Facades\Auth::user()->login }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        {{ _i('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/admin/layouts/footer.blade.php
<div class="row">
    <div class="col-12 text-center">
        <a href="https://github.com/puikinsh/ElaAdmin">Ela Admin</a> © {{ date('Y') }} {{ _i('All rights reserved') }}.
    </div>
</div>

resources/views/admin/layouts/header.blade.php
<div class="header">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ route('admin.dashboard')  }}">
                <b>
                    <img src="{{ asset('/admin/images/logo.png') }}" alt="homepage" class="dark-logo"/>
                </b>
                <span>
                    <img src="{{ asset('/admin/images/logo-text.png') }}" alt="homepage" class="dark-logo"/>
                </span>
            </a>
        </div>
        <div class="navbar-collapse">
            <ul class="navbar-nav mr-auto mt-md-0">
                <li class="nav-item">
                    <a class="nav-link nav-toggler hidden-md-up text-muted  " href="javascript:void(0)">
                        <i class="mdi mdi-menu">1717</i>
                    </a>
                </li>
                <li class="nav-item m-l-10">
                    <a class="nav-link sidebartoggler hidden-sm-down text-muted  " href="javascript:void(0)">
                        <i class="ti-menu">2222</i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-muted" href="{{ url('/') }}"><i class="ti-home"></i>
                        <span class="hidden-sm-down">{{ _i('Go to main page') }}</span>
                    </a>
                </li>
            </ul>
            <div class="navbar-nav my-lg-0">
                <div class="btn-group">
                    <a class="btn btn-outline-warning btn-sm" href="#">
                        <i class="fa fa-user"></i>
                        <img src="{{ asset('/admin/images/user.jpg') }}" alt="user" class="profile-pic"/>
                    </a>
                    <button type="button" class="btn btn-outline-info btn-sm dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="sr-only">{{ _i('User menu') }}</span>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="dropdown-divider"></div>
                        <a class="fa fas fa-sign-out-alt dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Выход
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

resources/views/admin/layouts/meta.blade.php
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

resources/views/admin/layouts/scripts.blade.php
<script src="{{ asset('/backend/jquery/jquery-3.4.1.min.js') }}"></script>
<script src="{{ asset('/backend/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('/admin/js/scripts.js') }}"></script>

@stack('custom_scripts')

resources/views/admin/layouts/sidebar.blade.php
<div class="scroll-sidebar">
    <a class="nav-link pl-1" href="{{ route('area_maps.index') }}">
        <i class="far fa-map"></i> {{ _i('Area maps') }}
    </a>
    <a class="nav-link pl-1" href="#" data-toggle="collapse" data-target="#submenu_areas" role="button" aria-expanded="true">
        <i class="fab fa-wpforms"></i> {{ _i('Area') }}
    </a>
    <div class="collapse show" id="submenu_areas">
        <ul class="flex-column pl-2 nav">
            <li class="nav-item py-1">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#raw-materials" role="button" aria-expanded="false">{{ _i('Raw materials') }}</a>
                <div class="collapse" id="raw-materials">
                    <ul class="flex-column pl-2 nav">
                        <li class="nav-item">
                            <a class="nav-link py-0" href="{{ route('raw_materials.index') }}">{{ _i('Raw materials') }}</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link py-1 collapsed" href="#" data-toggle="collapse" data-target="#buildings" role="button" aria-expanded="false">{{ _i('Buildings') }}</a>
                <div class="collapse" id="buildings">
                    <ul class="flex-column pl-2 nav">
                        <li class="nav-item">
                            <a class="nav-link py-0" href="{{ url('storage-buildings.create') }}">{{ _i('Storage buildings') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link py-0" href="{{ url('industrial-buildings.create') }}">{{ _i('Industrial buildings') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link py-0" href="{{ url('creative-buildings.create') }}">{{ _i('Creative buildings') }}</a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
            <div class="dropdown-divider"></div>
    <div class="collapse show" id="submenu2">
        {{ trans_choice('Example', 2) }}
        <ul class="flex-column pl-2 nav">
            <li class="nav-item">
                <a class="nav-link collapsed py-0" href="#submenu1sub1" data-toggle="collapse" data-target="#submenu1sub1">
                    Customers
                </a>
                <div class="collapse small" id="submenu1sub1" aria-expanded="false">
                    <ul class="flex-column nav pl-4">
                        <li class="nav-item">
                            <a class="nav-link p-0" href="">
                                <i class="fa fa-fw fa-clock"></i> Daily
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-0" href="">
                                <i class="fa fa-fw fa-tools"></i> Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-0" href="">
                                <i class="fa fa-fw fa-chart-bar"></i> Charts
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link p-0" href="">
                                <i class="fa fa-fw fa-compass"></i> Areas
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</div>

resources/views/admin/layouts/styles.blade.php
<link href="{{ asset('/backend/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ asset('/backend/fontawesome/css/all.min.css') }}" rel="stylesheet">
<link href="{{ asset('/backend/css/style-admin.css') }}" rel="stylesheet">

@stack('custom_styles')